# SPDX-License-Identifier: Apache-2.0
"""Stable contracts and historical tested releases (never membership gates)."""

ADAPTER_ID = "meridian.kafka"
ADAPTER_CONTRACT_VERSION = "1.0.0"
CLIENT_ID = "confluent-kafka"
CLIENT_VERSION = "2.15.0"
DRIVER = CLIENT_ID
PRODUCTION_ENGINE_PROFILE = "apache-kafka"
TEST_ENGINE_PROFILE = "apache-kafka-test"
SUPPORTED_ENGINE_VERSIONS = ("4.1.2", "4.2.1", "4.3.1")
MIGRATION_SOURCE_VERSIONS = ("3.9.2", "4.0.2")
TRANSACTION_OPERATION_CONTRACT = "meridian.streaming.transactional-consume-publish"
TRANSACTION_OPERATION_VERSION = "1.0.0"
CORE_TRANSACTION_CONTRACT = "meridian.transaction"
CORE_TRANSACTION_VERSION = "1.0.0"

__all__ = [
    "ADAPTER_CONTRACT_VERSION",
    "ADAPTER_ID",
    "CLIENT_ID",
    "CLIENT_VERSION",
    "CORE_TRANSACTION_CONTRACT",
    "CORE_TRANSACTION_VERSION",
    "DRIVER",
    "MIGRATION_SOURCE_VERSIONS",
    "PRODUCTION_ENGINE_PROFILE",
    "SUPPORTED_ENGINE_VERSIONS",
    "TEST_ENGINE_PROFILE",
    "TRANSACTION_OPERATION_CONTRACT",
    "TRANSACTION_OPERATION_VERSION",
]
